"""create ledger_entries table

Revision ID: e550ef2d24ac
Revises: 49f1e088d24e
Create Date: 2026-09-01 20:53:49.842998

This file is a migration (see the notes-table migration for what that
means). It creates the table that records every charge and refund — see
docs/specs/ledger.md for the rules this table's constraints are enforcing:
a unique idempotency_key (so Postgres itself refuses a repeated request),
a check that amounts are always positive, and a check that kind is only
ever "charge" or "refund".
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e550ef2d24ac'
down_revision: str | Sequence[str] | None = '49f1e088d24e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration: create the ledger_entries table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('charge_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('charge', 'refund')", name='ck_ledger_entries_kind_valid'),
    sa.CheckConstraint('amount_cents > 0', name='ck_ledger_entries_amount_positive'),
    sa.ForeignKeyConstraint(['charge_id'], ['ledger_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_ledger_entries_account_id'), 'ledger_entries', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo this migration: delete the ledger_entries table (and all its data!)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_entries_account_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    # ### end Alembic commands ###
